name: CF Login
description: Login to the Cloud Foundry CLI
runs:
  using: "composite"
  steps:
    - name: Log in to Cloud Foundry
      shell: bash
      run: |
        cf login -u ${{ inputs.cf-username }} -p ${{ inputs.cf-password }} -a api.fr.cloud.gov -o doi-onrr -s ${{ inputs.cf-space }}