name: CF Login
description: Login to the Cloud Foundry CLI
runs:
  using: "composite"
  steps:
    - name: Log in to Cloud Foundry
      shell: bash
      run: |
        cf login -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -a api.fr.cloud.gov -o doi-onrr -s ${{ inputs.cf-space }}