name: Deploy build to cloud.gov via CF CLI

on:
  workflow_call:
    inputs:
      cf-space:
        type: string
        default: dev
      
      manifest:
        type: string
        default: manifest.yml

      build-path:
        type: string
        default: ./public

    secrets:
      CF_USERNAME:
        required: true

      CF_PASSWORD:
        required: true
    
jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.build-path }}

      - name: Install CF CLI
        uses: doi-onrr/oddd-actions/.github/actions/cf-install@v1

      - name: Log in to Cloud Foundry
        shell: bash
        run: |
          cf login -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -a api.fr.cloud.gov -o doi-onrr -s ${{ inputs.cf-space }}

      - name: Push to Cloud Foundry
        shell: bash
        run: |
          cf push -f ${{ inputs.manifest }} -p ${{ inputs.build-path }}